version: '3.9'
name: stonks

services:
  postgres_db:
    image: postgres

    environment:
      POSTGRES_DB: stonks
      POSTGRES_PASSWORD: "qwerty"

    volumes:
      - ./internal/db/dumps:/dumps
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
  
#  migrator:
#    container_name: migrator
#    build:
#      context: ./
#      dockerfile: migrator/Dockerfile
#    depends_on:
#      - postgres_db
#    links:
#      - "postgres_db:db"
  api:
    container_name: stonks_runtime
    build: .
    ports:
      - "5167:5167"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://0.0.0.0:5167"
    depends_on:
      - postgres_db
    links:
      - "postgres_db:db"

volumes:
  postgres_data:

